title                    : "Danny Finn"
name                     : &name "Danny Finn"
description              : &description "Graduate researcher at University at Buffalo."
theme: jekyll-theme-cayman
