theme: jekyll-theme-cayman
locale: "en-US"
title: Danny Finn
description: Graduate researcher at University at Buffalo.
url: https://danofinn.github.io/danfinn.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "" # the subpath of your site, e.g. "/blog"
